package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"test-server/graph/model"
	"github.com/go-resty/resty/v2"
)

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, id string) (*model.Character, error) {
	apiClient := resty.New()

	resp, err := apiClient.R().
		SetResult(&model.Character{}).
		Get(fmt.Sprintf("https://swapi.dev/api/people/%s/", id))
	if err != nil {
		return nil, err
	}
	character := resp.Result().(*model.Character)
	return character, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
