// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	Name      *string `json:"name,omitempty"`
	Height    *string `json:"height,omitempty"`
	Mass      *string `json:"mass,omitempty"`
	Gender    *string `json:"gender,omitempty"`
	Homeworld *string `json:"homeworld,omitempty"`
	ID        *string `json:"id,omitempty"`
}

type Query struct {
}
