// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	Name      *string `json:"name,omitempty"`
	Height    *string `json:"height,omitempty"`
	Mass      *string `json:"mass,omitempty"`
	Gender    *string `json:"gender,omitempty"`
	Homeworld *string `json:"homeworld,omitempty"`
	ID        *string `json:"id,omitempty"`
}

type Mutation struct {
}

type NewVehicle struct {
	CargoCapacity        *string `json:"cargoCapacity,omitempty"`
	Consumables          *string `json:"consumables,omitempty"`
	CostInCredits        *string `json:"costInCredits,omitempty"`
	Crew                 *string `json:"crew,omitempty"`
	Length               *string `json:"length,omitempty"`
	Manufacturer         *string `json:"manufacturer,omitempty"`
	MaxAtmospheringSpeed *string `json:"maxAtmospheringSpeed,omitempty"`
	Model                *string `json:"model,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Passengers           *string `json:"passengers,omitempty"`
	VehicleClass         *string `json:"vehicleClass,omitempty"`
}

type Query struct {
}

type Vehicle struct {
	ID                   string  `json:"id"`
	CargoCapacity        *string `json:"cargoCapacity,omitempty"`
	Consumables          *string `json:"consumables,omitempty"`
	CostInCredits        *string `json:"costInCredits,omitempty"`
	Crew                 *string `json:"crew,omitempty"`
	Length               *string `json:"length,omitempty"`
	Manufacturer         *string `json:"manufacturer,omitempty"`
	MaxAtmospheringSpeed *string `json:"maxAtmospheringSpeed,omitempty"`
	Model                *string `json:"model,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Passengers           *string `json:"passengers,omitempty"`
	VehicleClass         *string `json:"vehicleClass,omitempty"`
}
